# Release Android App Bundle (.aab) for the Play Store, built locally and signed
# with the real upload key. Output: hooked\content\hooked-release.aab
#
# The sibling script local-android-build.ps1 produces an APK for sideloading and
# signs it with the *debug* key, which Play refuses. This one installs nothing —
# run that script first if the JDK/SDK aren't there yet.
#
# The keystore and its password live outside the repo, in %USERPROFILE%\.keystores,
# because /android is regenerated by prebuild and would drag them along.
$ErrorActionPreference = "Stop"
$log = { param($m) Write-Output ("[{0}] {1}" -f (Get-Date -Format HH:mm:ss), $m) }

$root = "C:\Users\minus\hooked"
$keyDir = "$env:USERPROFILE\.keystores"
$keystore = "$keyDir\hooked-upload.jks"
$pwFile = "$keyDir\hooked-upload.pw"

# ---- toolchain (already installed by local-android-build.ps1) ----
$jdkDir = Get-ChildItem "$env:USERPROFILE\.jdks" -Directory -Filter "jdk-17*" -ErrorAction SilentlyContinue |
  Select-Object -First 1
if (-not $jdkDir) { throw "No JDK 17 in ~\.jdks — run scripts\local-android-build.ps1 once first" }
$env:JAVA_HOME = $jdkDir.FullName
$env:Path = "$env:JAVA_HOME\bin;$env:Path"

$sdkRoot = "$env:LOCALAPPDATA\Android\Sdk"
if (-not (Test-Path "$sdkRoot\platform-tools")) { throw "No Android SDK — run scripts\local-android-build.ps1 once first" }
$env:ANDROID_HOME = $sdkRoot
& $log "JDK $($jdkDir.Name), SDK $sdkRoot"

# ---- signing credentials ----
if (-not (Test-Path $keystore)) { throw "No upload keystore at $keystore" }
if (-not (Test-Path $pwFile)) { throw "No password file at $pwFile" }
$pw = (Get-Content $pwFile -Raw).Trim()
$env:HOOKED_KEYSTORE = $keystore
$env:HOOKED_KEYSTORE_PASSWORD = $pw
$env:HOOKED_KEY_ALIAS = "hooked-upload"
$env:HOOKED_KEY_PASSWORD = $pw
& $log "signing with $keystore (alias hooked-upload)"

# ---- prebuild the native project ----
Set-Location "$root\mobile"
"sdk.dir=$($sdkRoot -replace '\\','/')" | Set-Content -Encoding ascii "local.properties.tmp"
& $log "expo prebuild..."
$env:CI = "1"
npx expo prebuild -p android --no-install
if ($LASTEXITCODE -ne 0) { throw "expo prebuild failed" }
Move-Item "local.properties.tmp" "android\local.properties" -Force

# Gradle 9 forbids project names ending in '.' — the launcher label still comes
# from resources, so only the internal name is sanitized.
$settings = "android\settings.gradle"
(Get-Content $settings -Raw) -replace "rootProject.name = 'hooked.'", "rootProject.name = 'hooked'" |
  Set-Content -Encoding ascii $settings

# ---- point the release build at the real key ----
# prebuild rewrites build.gradle every run, so this is applied here rather than
# committed. The config reads the environment and fails loudly if it's unset —
# a silent fall back to the debug key would produce an .aab that looks fine and
# is rejected on upload.
$gradleFile = "android\app\build.gradle"
$gradle = Get-Content $gradleFile -Raw
if ($gradle -notmatch "hookedUpload") {
  # ASCII only: this block is written out with -Encoding ascii, so anything
  # fancier than a hyphen lands in build.gradle as a question mark.
  $releaseConfig = @'
        release {
            // injected by scripts\local-android-bundle.ps1 - see that file
            def hookedUpload = System.getenv("HOOKED_KEYSTORE")
            if (!hookedUpload) {
                throw new GradleException("HOOKED_KEYSTORE is not set - build with scripts\\local-android-bundle.ps1, not gradlew directly")
            }
            storeFile file(hookedUpload)
            storePassword System.getenv("HOOKED_KEYSTORE_PASSWORD")
            keyAlias System.getenv("HOOKED_KEY_ALIAS")
            keyPassword System.getenv("HOOKED_KEY_PASSWORD")
        }
    }
'@
  # close the debug config, then append ours before the closing brace
  $gradle = $gradle -replace "(?s)(signingConfigs \{.*?keyPassword 'android'\s*\}\s*)\}", "`$1$releaseConfig"
  $gradle = $gradle -replace "(?s)(release \{\s*//[^\n]*\n\s*//[^\n]*\n\s*)signingConfig signingConfigs\.debug",
    "`$1signingConfig signingConfigs.release"
  Set-Content -Encoding ascii $gradleFile $gradle
  & $log "patched build.gradle for release signing"
}
if ((Get-Content $gradleFile -Raw) -notmatch "signingConfig signingConfigs\.release") {
  throw "build.gradle still points the release build at the debug key — the patch did not apply"
}

# ---- bundle ----
Set-Location "$root\mobile\android"
& $log "gradle bundleRelease (first run pulls gradle + deps + NDK — that's the slow part)..."
.\gradlew.bat bundleRelease --no-daemon
if ($LASTEXITCODE -ne 0) { throw "gradle bundleRelease failed" }

$aab = "$root\mobile\android\app\build\outputs\bundle\release\app-release.aab"
if (-not (Test-Path $aab)) { throw "no .aab at $aab" }

# ---- prove it's signed with the upload key, not the debug key ----
$verify = & "$env:JAVA_HOME\bin\jarsigner.exe" -verify -verbose:summary -certs $aab 2>&1 | Out-String
if ($verify -match "CN=Android Debug") { throw "that bundle is debug-signed — Play will reject it" }
if ($verify -notmatch "jar verified") { throw "jarsigner could not verify the bundle" }
& $log "signature verified, not the debug key"

New-Item -ItemType Directory -Force "$root\content" | Out-Null
Copy-Item $aab "$root\content\hooked-release.aab" -Force
$size = [Math]::Round((Get-Item "$root\content\hooked-release.aab").Length / 1MB, 1)
& $log "AAB READY: $root\content\hooked-release.aab (${size}MB)"
